FROM debian:oldstable-slim

COPY ./target/release/ebpf-extractor .

CMD ["./ebpf-extractor", "--nats-address", "127.0.0.1:4222", "--bitcoind-path", "/host/home/btc/.local/bin/bitcoind", "--bitcoind-pid-file", "/host/home/btc/.bitcoin/bitcoind.pid"]
